### PR TITLE
Support ignoring tables with RegExp

### PR DESCRIPTION
**Pull request by TonyGravagno**
In _mysql-zod.json_ a table name surrounded in slashes will now be treated as a regular expression.  
Example:   `"ignore": ["log","/^temp/"]`

- tableTemp = not ignored
- logfile = not ignored
- tempTable = ignored
- log = ignored
- templog = ignored

Changes to _main.js_ to support enhancement, and README updated.  
Also modified _.gitignore_ with common/important values.

_main.js_ is included because it's in the master _dist_ folder. Project was built with the build script in _package.json_.

### CODE REVIEW

**Comment by erwinstone** [comment]
Hi [TonyGravagno](https://github.com/TonyGravagno),

Thank you for submitting the pull request! I've reviewed your code, and it seems that it doesn't comply with our ESLint rules set for this project. ESLint helps us maintain code quality and consistency throughout the project.

To ensure consistency and readability, it would be great if you could make the necessary adjustments to align with our ESLint rules.

**Comment by TonyGravagno** [comment]
Dang, will check, thanks. I made sure to preserve original formatting, didn't look at other ESLint rules.

To be clear, this needs to comply with https://github.com/antfu/eslint-config ?

**Comment by TonyGravagno** [comment]
Please re-check and if it's OK I'll apply patch to other branches.

Thanks for processing this PR. As you have time, please look at the issues in my repo. I need those enhancements. Everything is optional, so the enhancements won't break your core. But if you don't want this package to get bloated then I'll keep my fork separate and you can decide which commits you prefer to cherry-pick.

**Comment by TonyGravagno** [comment]
Thanks, will lint other PRs and submit for review.

**Pull request merged**
